# This workflow handles automated releases when a tag is pushed
name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0

jobs:
  validate:
    name: Validate Release
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Cache Swift Package Manager
      uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-spm-release-${{ hashFiles('Package.swift') }}
        restore-keys: ${{ runner.os }}-spm-release-
        
    - name: Build and Test
      run: |
        swift build -c release
        swift test -c release
        
  create-release:
    name: Create GitHub Release
    runs-on: macos-latest
    needs: validate
    permissions:
      contents: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Get tag name
      id: get_tag
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_tag.outputs.TAG_NAME }}
        release_name: Release ${{ steps.get_tag.outputs.TAG_NAME }}
        body: |
          ## Changes
          
          See [CHANGELOG.md](CHANGELOG.md) for details.
          
          ## Installation
          
          ### Swift Package Manager
          
          Add PreviewInUIKit to your project:
          
          ```swift
          dependencies: [
              .package(url: "https://github.com/dwhao84/Preview-in-UIKit.git", from: "${{ steps.get_tag.outputs.TAG_NAME }}")
          ]
          ```
        draft: false
        prerelease: false